const DaddyGameTypes = {
    CREATE_ROOM: 'CREATE_ROOM',
    JOIN_ROOM: 'JOIN_ROOM',
    UPDATE_GAME_POSITIONS: 'UPDATE_GAME_POSITIONS',
    SWITCH_CURRENT_PLAYER: 'SWITCH_CURRENT_PLAYER',
    CANCEL_ROOM: 'CANCEL_ROOM',
    CREATE_PLAYER_NUMBER: 'CREATE_PLAYER_NUMBER',
    ADD_PLAYERS: 'ADD_PLAYERS',
    START_GAME: 'START_GAME'
};

export {
    DaddyGameTypes
}